### ISSUE TITLE
剧照顺序错误 Wrong extrafanart order

### ISSUE THREAD

**Issue by mrgne5** [glyh/JavSPn#15]
### 问题详情

剧照刮削的顺序错误

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by glyh** [comment]
可以提交一个番号复现方法吗？

**Comment by mrgne5** [comment]
> 可以提交一个番号复现方法吗？以及请问你用的是哪个版本？

我可能没表达好，是剧照刮削之后 并不是按刮削网址的顺序命名图片（刮削了任意8个都是如此） 用的最新版本

**Comment by glyh** [comment]
刚刚push了2.0.5，请试一下这里的artifact是否修复了bug（翻到最后面有个zip），如果修复了我会发一个release

https://github.com/glyh/JavSPn/actions/runs/8947422228/job/24579338340

**Comment by mrgne5** [comment]
> 刚刚push了2.0.5，请试一下这里的artifact是否修复了bug（翻到最后面有个zip），如果修复了我会发一个release
> 
> https://github.com/glyh/JavSPn/actions/runs/8947422228

剧照顺序问题已修复 
还有一个bug 就是使用翻译时 google能正常使用 但是调用baidu时会出错
2024-05-04 13:38:37 main:552 DEBUG: requests.api.post() got multiple values for keyword argument 'headers'
Traceback (most recent call last):
  File "javspn\__main__.py", line 470, in RunNormalMode
  File "D:\a\JavSPn\JavSPn\javspn\web\translate.py", line 27, in translate_movie_info
  File "D:\a\JavSPn\JavSPn\javspn\web\translate.py", line 63, in translate
  File "D:\a\JavSPn\JavSPn\javspn\web\translate.py", line 147, in baidu_translate
  File "D:\a\JavSPn\JavSPn\javspn\web\base.py", line 130, in request_post
TypeError: requests.api.post() got multiple values for keyword argument 'headers'
2024-05-04 13:38:37 main:553 ERROR: 整理失败: requests.api.post() got multiple values for keyword argument 'headers'

**Comment by glyh** [comment]
请测试 https://github.com/glyh/JavSPn/actions/runs/8948437721

**Comment by mrgne5** [comment]
> 请测试 https://github.com/glyh/JavSPn/actions/runs/8948437721

可以了 剧照图片顺序正常 且能正确使用baidu翻译
